version: "3.9"
services:
  hazelcast-0:
    image: hazelcast/hazelcast:latest
    environment:
      - HZ_CLUSTERNAME=demo-cluster

  hazelcast-1:
    image: hazelcast/hazelcast:latest
    environment:
      - HZ_CLUSTERNAME=demo-cluster

  app-0:
    image: security-and-error-handling-demo/app
    build: ..
    environment:
      - PORT=8080
      - HZ_CLUSTERNAME=demo-cluster
      - HZ_ADDRESSES=hazelcast-0,hazelcast-1

  app-1:
    image: security-and-error-handling-demo/app
    build: ..
    environment:
      - PORT=8080
      - HZ_CLUSTERNAME=demo-cluster
      - HZ_ADDRESSES=hazelcast-0,hazelcast-1

  gateway:
    image: security-and-error-handling-demo/gateway
    build: loadbalancer
    ports:
      - "9000:9000"
