version: "3.9"
name: "security-and-error-handling-demo"
services:
  hazelcast:
    image: hazelcast/hazelcast:latest
    restart: always
    environment:
      - HZ_CLUSTERNAME=demo-cluster
    deploy:
      replicas: 2

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=2smart4u
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=password123
      - MARIADB_DATABASE=appdb
    volumes:
      - datadir:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "9001:8080"

  app-0:
    image: security-and-error-handling-demo/app
    build: ..
    restart: always
    environment:
      - PORT=8080
      - HZ_CLUSTERNAME=demo-cluster
      - HZ_ADDRESSES=hazelcast
      - DATABASE_URL=jdbc:mariadb://db/appdb?user=appuser&password=password123&connectTimeout=5000
    depends_on:
      - db
      - hazelcast

  app-1:
    image: security-and-error-handling-demo/app
    build: ..
    restart: always
    environment:
      - PORT=8080
      - HZ_CLUSTERNAME=demo-cluster
      - HZ_ADDRESSES=hazelcast
      - DATABASE_URL=jdbc:mariadb://db/appdb?user=appuser&password=password123&connectTimeout=5000
    depends_on:
      - db
      - hazelcast

  gateway:
    image: security-and-error-handling-demo/gateway
    build: loadbalancer
    restart: always
    ports:
      - "9000:9000"

volumes:
  datadir:
